/** Safari ERP mobile tokens — aligned with the web SAFARI ERP identity. */
export const brand = {
  nameAr: 'SAFARI ERP',
  nameEn: 'Safari ERP Staff',
  colors: {
    primaryBlue: '#0F52BA',
    darkBlue: '#0A2A6C',
    cyan: '#38BDF8',
    lightCyan: '#E0F2FE',
    gold: '#D4AF37',
    goldSoft: '#F3E3A3',
    grayBackground: '#F8FAFC',
    surface: '#FFFFFF',
    surfaceMuted: '#F1F5F9',
    border: '#E2E8F0',
    borderStrong: '#CBD5E1',
    white: '#FFFFFF',
    text: '#172033',
    textMuted: '#64748B',
    textSoft: '#94A3B8',
    danger: '#DC2626',
    dangerSoft: '#FEE2E2',
    success: '#16A34A',
    successSoft: '#DCFCE7',
    warning: '#D97706',
    warningSoft: '#FEF3C7',
    neutralSoft: '#E2E8F0',
  },
  radius: {
    sm: 12,
    md: 16,
    lg: 20,
    xl: 24,
  },
  space: {
    xs: 6,
    sm: 10,
    md: 14,
    lg: 20,
    xl: 28,
  },
} as const;
