import type { NavGroup } from '@/modules/shared/nav/nav-types';
import {
  customersItem,
  dashboardItem,
  debtRecoveryReportItem,
  driverAuditRadarItem,
  expenseApprovalItem,
  knetAuditReportItem,
  driverMonitorItem,
  expensesItem,
  financialCycleReportItem,
  financialsItem,
  fixedExpensesItem,
  invoicesDataItem,
  manageItemsItem,
  managerCustodyAgingItem,
  ownerDashboardItem,
  ownerInventoryItem,
  ownerSerialsItem,
  myDailySalesItem,
  ordersItem,
  payrollItem,
  staffDebtsItem,
  posItem,
  reportsItem,
  shiftsItem,
  subscribersItem,
  subscriptionsItem,
  collectionsItem,
  teamItem,
} from '@/modules/shared/nav/nav-items';

/** Full navigation for OWNER, MANAGER, SUPERVISOR, VIEWER, WORKER, and default fallbacks. */
export const defaultSidebarNavGroups: NavGroup[] = [
  {
    labelKey: 'nav.groupMain',
    items: [
      posItem,
      ownerDashboardItem,
      manageItemsItem,
      ownerInventoryItem,
      dashboardItem,
      customersItem,
      myDailySalesItem,
      collectionsItem,
      subscriptionsItem,
      subscribersItem,
      driverAuditRadarItem,
      driverMonitorItem,
    ],
  },
  {
    labelKey: 'nav.groupOperations',
    items: [invoicesDataItem, ordersItem, shiftsItem, ownerSerialsItem],
  },
  {
    labelKey: 'nav.groupFinance',
    items: [
      financialsItem,
      knetAuditReportItem,
      expenseApprovalItem,
      financialCycleReportItem,
      managerCustodyAgingItem,
      staffDebtsItem,
      debtRecoveryReportItem,
      reportsItem,
      payrollItem,
      fixedExpensesItem,
      expensesItem,
    ],
  },
  { labelKey: 'nav.groupSettings', items: [teamItem] },
];
