import type { NavGroup } from '@/modules/shared/nav/nav-types';
import {
  bankDepositsItem,
  collectDriverCashItem,
  customersItem,
  dashboardItem,
  expenseApprovalItem,
  knetAuditItem,
  driverMonitorItem,
  expensesItem,
  financialCycleReportItem,
  financialsItem,
  fixedExpensesItem,
  manageItemsItem,
  ownerDashboardItem,
  myCashCustodyItem,
  myDailySalesItem,
  ordersItem,
  payrollItem,
  posItem,
  reportsItem,
  shiftsItem,
  subscribersItem,
  subscriptionsItem,
  collectionsItem,
  teamItem,
} from '@/modules/shared/nav/nav-items';

/** Full navigation for OWNER, MANAGER, SUPERVISOR, VIEWER, WORKER, and default fallbacks. */
export const defaultSidebarNavGroups: NavGroup[] = [
  {
    labelKey: 'nav.groupMain',
    items: [
      posItem,
      ownerDashboardItem,
      manageItemsItem,
      dashboardItem,
      customersItem,
      myDailySalesItem,
      myCashCustodyItem,
      collectionsItem,
      subscriptionsItem,
      subscribersItem,
      driverMonitorItem,
    ],
  },
  { labelKey: 'nav.groupOperations', items: [ordersItem, shiftsItem] },
  {
    labelKey: 'nav.groupFinance',
    items: [
      financialsItem,
      bankDepositsItem,
      knetAuditItem,
      expenseApprovalItem,
      financialCycleReportItem,
      collectDriverCashItem,
      reportsItem,
      payrollItem,
      fixedExpensesItem,
      expensesItem,
    ],
  },
  { labelKey: 'nav.groupSettings', items: [teamItem] },
];
